title:              David Tello
email:              davidtellop@gmail.com
baseurl:            "/Portfolio"
url:                "https://davidtello1.github.io"
cv_link:            "https://drive.google.com/file/d/1NuBw9qVHwQshNfjDnHMCua6JphiCoO8j/view?usp=sharing"

# Social Profiles
github_url:         "https://github.com/DavidTello1"
linkedin_url:       "https://www.linkedin.com/in/david-tello-65b076155/"
picture:            "img/Picture.png"

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site


# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:path/
    order:
      - grip-or-slip.html
      - command-and-conquer.html
      - davos-game-engine.html
      - the-witcher-ties-of-destiny.html
      - s-team.html
      - optimization-techniques-for-a-2D-engine.html
      - map-generator.html