title:              David Tello
email:              davidtellop@gmail.com
baseurl:            "/Portfolio"
url:                "https://davidtello1.github.io"
cv_link:            "https://drive.google.com/file/d/17Jn-alrhSACQwSxYkNrDSs9SRClI7r1o/view?usp=sharing"

# Social Profiles
github_url:         "https://github.com/DavidTello1"
linkedin_url:       "https://www.linkedin.com/in/david-tello-65b076155/"
picture:            "img/Picture.jpg"

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:path/
